<?php

namespace Bulliby\UserBundle\Repository;

/**
 * UserBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
