services:
    bulliby.user_manager:
        class: Bulliby\UserBundle\Model\UserManager
        arguments: ["@doctrine.orm.entity_manager"]
#    bulliby_user.example:
#        class: Bulliby\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
