services:
    bulliby.user_manager:
        class: Bulliby\UserBundle\Model\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]

    bulliby.user_notifications:
        class: Bulliby\UserBundle\EventListener\UserNotificationListener
        arguments: ["@security.password_encoder"]
        tags:
            - { name: kernel.event_subscriber }
