parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bulliby\UserBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Controller,DependencyInjection,Event,Form,Resources}'

    Bulliby\UserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
